version: '3.8'
services:
karate-tests:
image: karate-tests
build:
context: .
dockerfile: ./dockerfile
valumes:
- ./target:/usr/src/app/target
- ~/.m2:/root/m2
command: mvn test

#docker-compose up --build




